### PR TITLE
bumping parent

### PR DESCRIPTION
**Pull request by witokondoria**

### CODE REVIEW

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/crossbuilds-maven-plugin/366/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/crossbuilds-maven-plugin/372/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/crossbuilds-maven-plugin/389/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
