### PR TITLE
Adding javadoc and sources plugins

### PR DESCRIPTION
**Pull request by smola**
As sonatype wont accept the release

### CODE REVIEW

**Comment by smola** [comment]
Ported to master from: https://github.com/Stratio/scala-cross-build-maven-plugin/pull/39

**Comment by smola** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP.

**Comment by smola** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP.

**Comment by smola** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP.

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/crossbuilds-maven-plugin/355/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Comment by witokondoria** [comment]
:shipit:

**Comment by stratiocommit** [comment]
Comment accepted. Will treat it ASAP on [Jenkins](http://jenkins.stratio.com/job/Infra/job/crossbuilds-maven-plugin/384/)

**Comment by stratiocommit** [comment]
Rebase && testing in progress

**Pull request merged**
